name: Flutter CI

# This workflow is triggered on pushes to the repository.

on:
  push:
    branches:
    - ble
    
# on: push    # Default will running for every branch.
    
jobs:
  android:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '18.x'
    
    - name: Setup flutter
      uses: subosito/flutter-action@v1
      with:
        channel: 'stable' # 'dev', 'alpha', default to: 'stable'
    
    - name: Get dependencies
      run: |
        cd jolly_programmer_frontend
        flutter pub get

    - name: Build
      run: |
        cd jolly_programmer_frontend
        flutter build apk
    
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: release-android
        path: jolly_programmer_frontend/build/app/outputs/apk/release/app-release.apk

  windows:
    runs-on: windows-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '18.x'
    
    - name: Setup flutter
      uses: subosito/flutter-action@v1
      with:
        channel: 'stable' # 'dev', 'alpha', default to: 'stable'
    
    - name: Get dependencies
      run: |
        cd jolly_programmer_frontend
        flutter pub get

    - name: Build
      run: |
        cd jolly_programmer_frontend
        flutter build windows --release

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: release-win64
        path: jolly_programmer_frontend/build/windows/x64/runner/Release

  macos:
    runs-on: macos-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '18.x'
    
    - name: Setup flutter
      uses: subosito/flutter-action@v1
      with:
        channel: 'stable' # 'dev', 'alpha', default to: 'stable'
    
    - name: Get dependencies
      run: |
        cd jolly_programmer_frontend
        flutter pub get

    - name: Build
      run: |
        cd jolly_programmer_frontend
        flutter build macos --release
        mkdir output
        mv build/macos/Build/Products/Release/jolly_programmer_frontend.app output

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: release-macos
        path: jolly_programmer_frontend/output

    
